feat: rate comic
MaskingTechnology/comify pull request #170
Opened 2024-04-05 22:47 UTC by basmasking

Fixes #156 

@MaskingTechnology/comify

2024-04-06 10:34 UTC, petermasking requested changes

2024-04-06 10:34 UTC, petermasking commented on src/domain/post/data/retrieve.ts
> +    console.log('retrieve', id);
```suggestion
```

2024-04-06 10:34 UTC, petermasking commented on test/domain/post/_fixtures/toggleRating.fixture.ts
Is there a specific reason why the toggle rating function has it's own fixture? Ow can we merge it into the post fixture?

2024-04-06 10:34 UTC, petermasking commented on test/domain/post/toggleRating.spec.ts
The rollback of the saga isn't tested in this spec yet. Can you add one? For an example you can look at the `establish.spec` file in the relation module.

2024-04-06 15:02 UTC, basmasking commented on test/domain/post/_fixtures/toggleRating.fixture.ts
As discussed, we leave this for now and discuss on Monday

2024-04-07 11:37 UTC, petermasking approved these changes

2024-04-07 11:37 UTC, merged