feat(web-ui): remove reaction
MaskingTechnology/comify pull request #200
Opened 2024-04-27 15:40 UTC by basmasking

Fixes #162

Changes proposed in this pull request:
- updated data definition for soft delete
- get non-deleted reactions only
- renamed `creator` to `relation` in view model to match view type
- added delete action to UI

@MaskingTechnology/comify

2024-04-29 12:10 UTC, petermasking requested changes

2024-04-29 12:10 UTC, petermasking commented on src/webui/components/reaction/Delete.tsx
> +    return <ClickArea clickHandler={deleteHandler}>
As discussed, we need to split this up into a `DeleteIcon` and a `DeleteButton`.

2024-04-29 12:10 UTC, petermasking commented on test/domain/reaction/remove.spec.ts
> +    });
I miss a test scenario for testing not retrieving deleted reactions.

2024-05-01 18:58 UTC, basmasking commented on src/domain/reaction/view/ReactionView.ts
> +    constructor(id: string, createdAt: Date, relation: RelationView, ratingCount: number, hasRated: boolean, comic?: ComicView, comment?: CommentView)
I've reverted the change and kept it to creator. In the context of the item itself it might be a better description than relation.

2024-05-02 07:48 UTC, petermasking requested changes

2024-05-02 07:48 UTC, petermasking commented on src/webui/hooks/useDeleteReaction.ts
> +        setReactions(result);
```suggestion
        const result = reactions.filter(item => item.id !== reaction.id);

        setReactions(result);

        await remove(johnDoe, reaction.id);
```

I've moved the actual delete below the visual delete to improve interaction and prevent multiple delete attempts when the connection is slow.

2024-05-02 07:48 UTC, petermasking commented on test/domain/reaction/_fixtures/reaction.fixture.ts
> +export { COMIC_DATA_URL, COMIC_RECORD_TYPE, COMMENT_MESSAGE, COMMENT_RECORD_TYPE, EXISTING_REQUESTER, IMAGE_RECORD_TYPE, NOT_EXISTING_POST_ID, POST_ID, POST_RECORD_TYPE, REACTION_RECORD_TYPE, createC
```suggestion
export {
    COMIC_RECORD_TYPE, COMMENT_RECORD_TYPE, POST_RECORD_TYPE, REACTION_RECORD_TYPE, IMAGE_RECORD_TYPE, 
    COMIC_DATA_URL,  COMMENT_MESSAGE, , EXISTING_REQUESTER, NOT_EXISTING_POST_ID, POST_ID,
    createComicReaction, createCommentReaction, createDatabase, createFileStorage, getByPost, remove };
```

2024-05-02 07:48 UTC, petermasking commented on test/domain/reaction/_fixtures/reaction.fixture.ts
>  import createComic from '^/domain/reaction/createComic';
```suggestion
import createComicReaction from '^/domain/reaction/createComic';
```

2024-05-02 07:48 UTC, petermasking commented on test/domain/reaction/getByPost.spec.ts
> +        await remove(EXISTING_REQUESTER, reaction.id);
This test currently also tests the remove function. Is it an option to alter the test database to also contain deleted reactions and test if they are not a part of the result instead?

2024-05-02 07:48 UTC, petermasking commented on test/domain/reaction/remove.spec.ts
> +        const reaction = await createCommentReaction(EXISTING_REQUESTER, POST_ID, COMMENT_MESSAGE);
Why is the comment created here? We commonly prepare the complete database in the fixture so we keep our tests clean and focused.

2024-05-02 11:09 UTC, petermasking approved these changes

2024-05-02 11:09 UTC, petermasking commented on src/domain/reaction/remove.ts
> +    const updatedPost = currentData.delete();
Besides deleting the reaction, we also should update the post reaction count.

2024-05-02 11:12 UTC, petermasking requested changes

2024-05-02 11:12 UTC, petermasking commented on src/domain/reaction/remove.ts
> +    const updatedPost = currentData.delete();
Besides deleting the reaction, we also should update the post reaction count.

2024-05-02 12:09 UTC, petermasking commented on test/domain/reaction/remove.spec.ts
> +import { COMIC_REACTION_ID, COMIC_RECORD_TYPE, COMMENT_REACTION_ID, COMMENT_RECORD_TYPE, DELETED_REACTION_ID, EXISTING_REQUESTER, REACTION_COMIC_ID, REACTION_COMMENT_ID, REACTION_RECORD_TYPE, Reactio
Should we also split this into multiple lines?

2024-05-02 12:12 UTC, petermasking commented on test/domain/reaction/remove.spec.ts
> +        expect(comment.deleted).toBeUndefined();
I don't think we should test the things we haven't implemented. Maybe we can place a comment in the delete function that we've chosen to only soft-delete the reaction, and not its children.

2024-05-02 12:16 UTC, petermasking commented on test/domain/reaction/remove.spec.ts
> +    it('should not delete already deleted reaction', async () =>
```suggestion
    it('should not delete an already deleted reaction', async () =>
```

2024-05-02 12:16 UTC, petermasking commented on test/domain/reaction/remove.spec.ts
> +    it('should not delete other creator reaction', async () =>
```suggestion
    it('should not delete a reaction from another creator', async () =>
```

2024-05-02 12:44 UTC, petermasking approved these changes

2024-05-02 12:44 UTC, merged