feat(domain): deleted not part of the data model
MaskingTechnology/comify pull request #223
Opened 2024-05-12 19:33 UTC by basmasking

Fixes #222

Changes proposed in this pull request:
- made distinction between remove and erase data
- fixed inconsistency with setting of date value
- fixed inconsistency with querying relations

@petermasking and @JohnatMasking I like both of your reviews for this pull request.

2024-05-13 08:11 UTC, petermasking requested changes

2024-05-13 12:18 UTC, basmasking commented on src/domain/reaction/data/mapRecord.ts
> +        new Date(record.createdAt as string)
@petermasking as discussed, we will use a string for all dates. So this Date change will be reverted and other parts of the data model will be updated with the ISO Date string values.

2024-05-13 12:42 UTC, petermasking requested changes

2024-05-13 12:42 UTC, petermasking commented on src/domain/reaction/data/remove.ts
> +    const updatedData = { ...post, deleted: true };
```suggestion
    const updatedData: RecordData = { ...post, deleted: true };
```

😉

2024-05-13 12:46 UTC, petermasking approved these changes

2024-05-14 14:11 UTC, JohnatMasking reviewed
All clear.

2024-05-14 14:12 UTC, JohnatMasking approved these changes
All agreed. No comments

2024-05-14 15:19 UTC, merged