chore(qa): Set up testing and linting
MaskingTechnology/comify pull request #5
Opened 2023-09-13 13:15 UTC by petermasking

What I've done:

* Set up testing
* Set up linting
* Set up GitHub Actions
   * Dependabot
   * CodeQL workflow
   * Node.js CI workflow (build, test, lint)

2023-09-21 18:26 UTC, BasMasking requested changes

2023-09-21 18:26 UTC, BasMasking commented on tsconfig.json
Why have you included the test folder to the include path? Vitest automatically throws an error when running a test that itsn't valid typescript.

The result of this change is a different structure in the dist folder. The server cannot start as the jitar.js file it is looking for is located in the `dist/src/` in stead of the `dist/` folder it expects now.

2023-10-02 09:47 UTC, BasMasking requested changes
I've added a comment about the vite.config.js file, which is probably generated during the build step. This file is already present as a .ts file.

2023-10-02 09:47 UTC, BasMasking commented on vite.config.js
The vite config is already present as a .ts file. I expect that the build step automatically transpiles this file into a .js file as well.

I don't expect this .js file to be here. Could you check the build configuration and remove the .js file?

2023-10-02 10:18 UTC, petermasking commented on vite.config.js
Great find! While playing around with the new setup, .js files where accidentally generated in the src folder. I've removed most of them, but missed this one.

2023-10-02 10:22 UTC, BasMasking approved these changes

2023-10-02 10:22 UTC, merged